name       : python-pysol-cards
version    : 0.14.3
release    : 10
source     :
    - https://files.pythonhosted.org/packages/source/p/pysol_cards/pysol_cards-0.14.3.tar.gz : b0fbfd38615bfc6fd755dab58505a9ae162d0da1866c25ca9141938b5823f061
homepage   : https://github.com/shlomif/pysol_cards
license    : MIT
component  : programming.python
summary    : Deal PySol FC Cards
description: |
    The pysol-cards python modules allow the python developer to generate the initial deals of some PySol FC games. It also supports PySol legacy deals and Microsoft FreeCell/Freecell Pro deals.
builddeps  :
    - pbr
    - python-random2
rundeps    :
    - pbr
    - python-random2
    - python-six
build      : |
    %python3_setup
install    : |
    %python3_install
