name       : python-pysol-cards
version    : 0.8.6
release    : 2
source     :
    - ? https://files.pythonhosted.org/packages/f4/f0/822c4db5a2fa9b29e01dd7485c1fd3bf70a2fba6e03fb38a04127d9a9017/pysol_cards-0.8.6.tar.gz
     : 6e536a60fad9a59d5ecc197b0a22718fa8b16de42ede37caa8f7b87b8e256148
license    : MIT
component  : programming.python
summary    : Deal PySol FC Cards
description: |
    The pysol-cards python modules allow the python developer to generate the initial deals of some PySol FC games. It also supports PySol legacy deals and Microsoft FreeCell/Freecell Pro deals.
builddeps  :
    - pbr
rundeps    :
    - pbr
    - python-six
build      : |
    %python3_setup
install    : |
    %python3_install
