name       : python-pysol-cards
version    : 0.12.0
release    : 7
source     :
    - https://files.pythonhosted.org/packages/source/p/pysol_cards/pysol_cards-0.12.0.tar.gz : 3c79baa3a48cf26f3ee6ff836b723f3a92f6cebf12d500dcaf504591a6fdbdda
homepage   : https://github.com/shlomif/pysol_cards
license    : MIT
component  : programming.python
summary    : Deal PySol FC Cards
description: |
    The pysol-cards python modules allow the python developer to generate the initial deals of some PySol FC games. It also supports PySol legacy deals and Microsoft FreeCell/Freecell Pro deals.
builddeps  :
    - pbr
    - python-random2
rundeps    :
    - pbr
    - python-random2
    - python-six
build      : |
    %python3_setup
install    : |
    %python3_install
