name       : python-pysol-cards
version    : 0.10.2
release    : 6
source     :
    - https://files.pythonhosted.org/packages/source/p/pysol_cards/pysol_cards-0.10.2.tar.gz : 2e9f5bfe5b6df3760ca274731e92820423066831df6351bbfdf832e32bbcc76e
homepage   : https://github.com/shlomif/pysol_cards
license    : MIT
component  : programming.python
summary    : Deal PySol FC Cards
description: |
    The pysol-cards python modules allow the python developer to generate the initial deals of some PySol FC games. It also supports PySol legacy deals and Microsoft FreeCell/Freecell Pro deals.
builddeps  :
    - pbr
    - python-random2
rundeps    :
    - pbr
    - python-random2
    - python-six
build      : |
    %python3_setup
install    : |
    %python3_install
